# Generated by Django 5.2.5 on 2025-12-13 12:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('repo_url', models.URLField()),
                ('subdomain', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('deploying', 'Deploying'), ('running', 'Running'), ('stopped', 'Stopped'), ('failed', 'Failed')], default='deploying', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_deployed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
                ('build_file', models.FileField(blank=True, null=True, upload_to='app_builds/'))
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
