# Generated by Django 5.2.5 on 2025-12-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='buildnumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
